/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated/_dashboard-layout'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AuthenticatedDashboardLayoutIndexRouteImport } from './routes/_authenticated/_dashboard-layout/index'
import { Route as AuthenticatedDashboardLayoutMyProjectsRouteImport } from './routes/_authenticated/_dashboard-layout/MyProjects'
import { Route as AuthenticatedDashboardLayoutInventoryRouteImport } from './routes/_authenticated/_dashboard-layout/Inventory'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardLayoutIndexRoute =
  AuthenticatedDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutMyProjectsRoute =
  AuthenticatedDashboardLayoutMyProjectsRouteImport.update({
    id: '/MyProjects',
    path: '/MyProjects',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutInventoryRoute =
  AuthenticatedDashboardLayoutInventoryRouteImport.update({
    id: '/Inventory',
    path: '/Inventory',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/Inventory': typeof AuthenticatedDashboardLayoutInventoryRoute
  '/MyProjects': typeof AuthenticatedDashboardLayoutMyProjectsRoute
  '/': typeof AuthenticatedDashboardLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/Inventory': typeof AuthenticatedDashboardLayoutInventoryRoute
  '/MyProjects': typeof AuthenticatedDashboardLayoutMyProjectsRoute
  '/': typeof AuthenticatedDashboardLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRoute
  '/_authenticated/_dashboard-layout': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_dashboard-layout/Inventory': typeof AuthenticatedDashboardLayoutInventoryRoute
  '/_authenticated/_dashboard-layout/MyProjects': typeof AuthenticatedDashboardLayoutMyProjectsRoute
  '/_authenticated/_dashboard-layout/': typeof AuthenticatedDashboardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/onboarding'
    | '/Inventory'
    | '/MyProjects'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/onboarding'
    | '/Inventory'
    | '/MyProjects'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(public)/login'
    | '/(public)/register'
    | '/_authenticated/_dashboard-layout'
    | '/_authenticated/onboarding'
    | '/_authenticated/_dashboard-layout/Inventory'
    | '/_authenticated/_dashboard-layout/MyProjects'
    | '/_authenticated/_dashboard-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard-layout': {
      id: '/_authenticated/_dashboard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard-layout/': {
      id: '/_authenticated/_dashboard-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/MyProjects': {
      id: '/_authenticated/_dashboard-layout/MyProjects'
      path: '/MyProjects'
      fullPath: '/MyProjects'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutMyProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/Inventory': {
      id: '/_authenticated/_dashboard-layout/Inventory'
      path: '/Inventory'
      fullPath: '/Inventory'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutInventoryRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
  }
}

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardLayoutInventoryRoute: typeof AuthenticatedDashboardLayoutInventoryRoute
  AuthenticatedDashboardLayoutMyProjectsRoute: typeof AuthenticatedDashboardLayoutMyProjectsRoute
  AuthenticatedDashboardLayoutIndexRoute: typeof AuthenticatedDashboardLayoutIndexRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardLayoutInventoryRoute:
      AuthenticatedDashboardLayoutInventoryRoute,
    AuthenticatedDashboardLayoutMyProjectsRoute:
      AuthenticatedDashboardLayoutMyProjectsRoute,
    AuthenticatedDashboardLayoutIndexRoute:
      AuthenticatedDashboardLayoutIndexRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardLayoutRoute:
    AuthenticatedDashboardLayoutRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
