/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated/_dashboard-layout'
import { Route as AuthenticatedDashboardLayoutIndexRouteImport } from './routes/_authenticated/_dashboard-layout/index'
import { Route as AuthenticatedDashboardLayoutMyProjectsRouteImport } from './routes/_authenticated/_dashboard-layout/MyProjects'
import { Route as AuthenticatedDashboardLayoutInventoryRouteImport } from './routes/_authenticated/_dashboard-layout/Inventory'
import { Route as publicAuthRegisterRouteImport } from './routes/(public)/auth/register'
import { Route as publicAuthLoginRouteImport } from './routes/(public)/auth/login'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardLayoutIndexRoute =
  AuthenticatedDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutMyProjectsRoute =
  AuthenticatedDashboardLayoutMyProjectsRouteImport.update({
    id: '/MyProjects',
    path: '/MyProjects',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutInventoryRoute =
  AuthenticatedDashboardLayoutInventoryRouteImport.update({
    id: '/Inventory',
    path: '/Inventory',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const publicAuthRegisterRoute = publicAuthRegisterRouteImport.update({
  id: '/(public)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthLoginRoute = publicAuthLoginRouteImport.update({
  id: '/(public)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/Inventory': typeof AuthenticatedDashboardLayoutInventoryRoute
  '/MyProjects': typeof AuthenticatedDashboardLayoutMyProjectsRoute
  '/': typeof AuthenticatedDashboardLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/Inventory': typeof AuthenticatedDashboardLayoutInventoryRoute
  '/MyProjects': typeof AuthenticatedDashboardLayoutMyProjectsRoute
  '/': typeof AuthenticatedDashboardLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_dashboard-layout': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/(public)/auth/login': typeof publicAuthLoginRoute
  '/(public)/auth/register': typeof publicAuthRegisterRoute
  '/_authenticated/_dashboard-layout/Inventory': typeof AuthenticatedDashboardLayoutInventoryRoute
  '/_authenticated/_dashboard-layout/MyProjects': typeof AuthenticatedDashboardLayoutMyProjectsRoute
  '/_authenticated/_dashboard-layout/': typeof AuthenticatedDashboardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/login'
    | '/auth/register'
    | '/Inventory'
    | '/MyProjects'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/login' | '/auth/register' | '/Inventory' | '/MyProjects' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_dashboard-layout'
    | '/(public)/auth/login'
    | '/(public)/auth/register'
    | '/_authenticated/_dashboard-layout/Inventory'
    | '/_authenticated/_dashboard-layout/MyProjects'
    | '/_authenticated/_dashboard-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  publicAuthLoginRoute: typeof publicAuthLoginRoute
  publicAuthRegisterRoute: typeof publicAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard-layout': {
      id: '/_authenticated/_dashboard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard-layout/': {
      id: '/_authenticated/_dashboard-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/MyProjects': {
      id: '/_authenticated/_dashboard-layout/MyProjects'
      path: '/MyProjects'
      fullPath: '/MyProjects'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutMyProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/Inventory': {
      id: '/_authenticated/_dashboard-layout/Inventory'
      path: '/Inventory'
      fullPath: '/Inventory'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutInventoryRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/(public)/auth/register': {
      id: '/(public)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof publicAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/login': {
      id: '/(public)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof publicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardLayoutInventoryRoute: typeof AuthenticatedDashboardLayoutInventoryRoute
  AuthenticatedDashboardLayoutMyProjectsRoute: typeof AuthenticatedDashboardLayoutMyProjectsRoute
  AuthenticatedDashboardLayoutIndexRoute: typeof AuthenticatedDashboardLayoutIndexRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardLayoutInventoryRoute:
      AuthenticatedDashboardLayoutInventoryRoute,
    AuthenticatedDashboardLayoutMyProjectsRoute:
      AuthenticatedDashboardLayoutMyProjectsRoute,
    AuthenticatedDashboardLayoutIndexRoute:
      AuthenticatedDashboardLayoutIndexRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardLayoutRoute:
    AuthenticatedDashboardLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  publicAuthLoginRoute: publicAuthLoginRoute,
  publicAuthRegisterRoute: publicAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
