/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPurchaseSuccessRouteImport } from './routes/_authenticated/purchase-success'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated/_dashboard-layout'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AuthenticatedDashboardLayoutSettingsRouteImport } from './routes/_authenticated/_dashboard-layout/settings'
import { Route as AuthenticatedDashboardLayoutListingsRouteImport } from './routes/_authenticated/_dashboard-layout/listings'
import { Route as AuthenticatedDashboardLayoutHistoryRouteImport } from './routes/_authenticated/_dashboard-layout/history'
import { Route as AuthenticatedDashboardLayoutExploreRouteImport } from './routes/_authenticated/_dashboard-layout/explore'
import { Route as AuthenticatedDashboardLayoutPortfolioIndexRouteImport } from './routes/_authenticated/_dashboard-layout/portfolio/index'
import { Route as AuthenticatedDashboardLayoutPortfolioTransactionsRouteImport } from './routes/_authenticated/_dashboard-layout/portfolio/transactions'
import { Route as AuthenticatedDashboardLayoutPortfolioTransferProjectIdRouteImport } from './routes/_authenticated/_dashboard-layout/portfolio/transfer.$projectId'
import { Route as AuthenticatedDashboardLayoutPortfolioRetireProjectIdRouteImport } from './routes/_authenticated/_dashboard-layout/portfolio/retire.$projectId'
import { Route as AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRouteImport } from './routes/_authenticated/_dashboard-layout/portfolio/project.$holdingId'
import { Route as AuthenticatedDashboardLayoutPortfolioListProjectIdRouteImport } from './routes/_authenticated/_dashboard-layout/portfolio/list.$projectId'
import { Route as AuthenticatedDashboardLayoutSourceListingListingIdRouteImport } from './routes/_authenticated/_dashboard-layout/$source/listing.$listingId_'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPurchaseSuccessRoute =
  AuthenticatedPurchaseSuccessRouteImport.update({
    id: '/purchase-success',
    path: '/purchase-success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardLayoutSettingsRoute =
  AuthenticatedDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutListingsRoute =
  AuthenticatedDashboardLayoutListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutHistoryRoute =
  AuthenticatedDashboardLayoutHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutExploreRoute =
  AuthenticatedDashboardLayoutExploreRouteImport.update({
    id: '/explore',
    path: '/explore',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutPortfolioIndexRoute =
  AuthenticatedDashboardLayoutPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutPortfolioTransactionsRoute =
  AuthenticatedDashboardLayoutPortfolioTransactionsRouteImport.update({
    id: '/portfolio/transactions',
    path: '/portfolio/transactions',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutPortfolioTransferProjectIdRoute =
  AuthenticatedDashboardLayoutPortfolioTransferProjectIdRouteImport.update({
    id: '/portfolio/transfer/$projectId',
    path: '/portfolio/transfer/$projectId',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutPortfolioRetireProjectIdRoute =
  AuthenticatedDashboardLayoutPortfolioRetireProjectIdRouteImport.update({
    id: '/portfolio/retire/$projectId',
    path: '/portfolio/retire/$projectId',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRoute =
  AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRouteImport.update({
    id: '/portfolio/project/$holdingId',
    path: '/portfolio/project/$holdingId',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutPortfolioListProjectIdRoute =
  AuthenticatedDashboardLayoutPortfolioListProjectIdRouteImport.update({
    id: '/portfolio/list/$projectId',
    path: '/portfolio/list/$projectId',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutSourceListingListingIdRoute =
  AuthenticatedDashboardLayoutSourceListingListingIdRouteImport.update({
    id: '/$source/listing/$listingId_',
    path: '/$source/listing/$listingId',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/purchase-success': typeof AuthenticatedPurchaseSuccessRoute
  '/explore': typeof AuthenticatedDashboardLayoutExploreRoute
  '/history': typeof AuthenticatedDashboardLayoutHistoryRoute
  '/listings': typeof AuthenticatedDashboardLayoutListingsRoute
  '/settings': typeof AuthenticatedDashboardLayoutSettingsRoute
  '/portfolio/transactions': typeof AuthenticatedDashboardLayoutPortfolioTransactionsRoute
  '/portfolio': typeof AuthenticatedDashboardLayoutPortfolioIndexRoute
  '/$source/listing/$listingId': typeof AuthenticatedDashboardLayoutSourceListingListingIdRoute
  '/portfolio/list/$projectId': typeof AuthenticatedDashboardLayoutPortfolioListProjectIdRoute
  '/portfolio/project/$holdingId': typeof AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRoute
  '/portfolio/retire/$projectId': typeof AuthenticatedDashboardLayoutPortfolioRetireProjectIdRoute
  '/portfolio/transfer/$projectId': typeof AuthenticatedDashboardLayoutPortfolioTransferProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/purchase-success': typeof AuthenticatedPurchaseSuccessRoute
  '/explore': typeof AuthenticatedDashboardLayoutExploreRoute
  '/history': typeof AuthenticatedDashboardLayoutHistoryRoute
  '/listings': typeof AuthenticatedDashboardLayoutListingsRoute
  '/settings': typeof AuthenticatedDashboardLayoutSettingsRoute
  '/portfolio/transactions': typeof AuthenticatedDashboardLayoutPortfolioTransactionsRoute
  '/portfolio': typeof AuthenticatedDashboardLayoutPortfolioIndexRoute
  '/$source/listing/$listingId': typeof AuthenticatedDashboardLayoutSourceListingListingIdRoute
  '/portfolio/list/$projectId': typeof AuthenticatedDashboardLayoutPortfolioListProjectIdRoute
  '/portfolio/project/$holdingId': typeof AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRoute
  '/portfolio/retire/$projectId': typeof AuthenticatedDashboardLayoutPortfolioRetireProjectIdRoute
  '/portfolio/transfer/$projectId': typeof AuthenticatedDashboardLayoutPortfolioTransferProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRoute
  '/_authenticated/_dashboard-layout': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/purchase-success': typeof AuthenticatedPurchaseSuccessRoute
  '/_authenticated/_dashboard-layout/explore': typeof AuthenticatedDashboardLayoutExploreRoute
  '/_authenticated/_dashboard-layout/history': typeof AuthenticatedDashboardLayoutHistoryRoute
  '/_authenticated/_dashboard-layout/listings': typeof AuthenticatedDashboardLayoutListingsRoute
  '/_authenticated/_dashboard-layout/settings': typeof AuthenticatedDashboardLayoutSettingsRoute
  '/_authenticated/_dashboard-layout/portfolio/transactions': typeof AuthenticatedDashboardLayoutPortfolioTransactionsRoute
  '/_authenticated/_dashboard-layout/portfolio/': typeof AuthenticatedDashboardLayoutPortfolioIndexRoute
  '/_authenticated/_dashboard-layout/$source/listing/$listingId_': typeof AuthenticatedDashboardLayoutSourceListingListingIdRoute
  '/_authenticated/_dashboard-layout/portfolio/list/$projectId': typeof AuthenticatedDashboardLayoutPortfolioListProjectIdRoute
  '/_authenticated/_dashboard-layout/portfolio/project/$holdingId': typeof AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRoute
  '/_authenticated/_dashboard-layout/portfolio/retire/$projectId': typeof AuthenticatedDashboardLayoutPortfolioRetireProjectIdRoute
  '/_authenticated/_dashboard-layout/portfolio/transfer/$projectId': typeof AuthenticatedDashboardLayoutPortfolioTransferProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/onboarding'
    | '/purchase-success'
    | '/explore'
    | '/history'
    | '/listings'
    | '/settings'
    | '/portfolio/transactions'
    | '/portfolio'
    | '/$source/listing/$listingId'
    | '/portfolio/list/$projectId'
    | '/portfolio/project/$holdingId'
    | '/portfolio/retire/$projectId'
    | '/portfolio/transfer/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/onboarding'
    | '/purchase-success'
    | '/explore'
    | '/history'
    | '/listings'
    | '/settings'
    | '/portfolio/transactions'
    | '/portfolio'
    | '/$source/listing/$listingId'
    | '/portfolio/list/$projectId'
    | '/portfolio/project/$holdingId'
    | '/portfolio/retire/$projectId'
    | '/portfolio/transfer/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(public)/login'
    | '/(public)/register'
    | '/_authenticated/_dashboard-layout'
    | '/_authenticated/onboarding'
    | '/_authenticated/purchase-success'
    | '/_authenticated/_dashboard-layout/explore'
    | '/_authenticated/_dashboard-layout/history'
    | '/_authenticated/_dashboard-layout/listings'
    | '/_authenticated/_dashboard-layout/settings'
    | '/_authenticated/_dashboard-layout/portfolio/transactions'
    | '/_authenticated/_dashboard-layout/portfolio/'
    | '/_authenticated/_dashboard-layout/$source/listing/$listingId_'
    | '/_authenticated/_dashboard-layout/portfolio/list/$projectId'
    | '/_authenticated/_dashboard-layout/portfolio/project/$holdingId'
    | '/_authenticated/_dashboard-layout/portfolio/retire/$projectId'
    | '/_authenticated/_dashboard-layout/portfolio/transfer/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchase-success': {
      id: '/_authenticated/purchase-success'
      path: '/purchase-success'
      fullPath: '/purchase-success'
      preLoaderRoute: typeof AuthenticatedPurchaseSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard-layout': {
      id: '/_authenticated/_dashboard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard-layout/settings': {
      id: '/_authenticated/_dashboard-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/listings': {
      id: '/_authenticated/_dashboard-layout/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutListingsRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/history': {
      id: '/_authenticated/_dashboard-layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/explore': {
      id: '/_authenticated/_dashboard-layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutExploreRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/portfolio/': {
      id: '/_authenticated/_dashboard-layout/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutPortfolioIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/portfolio/transactions': {
      id: '/_authenticated/_dashboard-layout/portfolio/transactions'
      path: '/portfolio/transactions'
      fullPath: '/portfolio/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutPortfolioTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/portfolio/transfer/$projectId': {
      id: '/_authenticated/_dashboard-layout/portfolio/transfer/$projectId'
      path: '/portfolio/transfer/$projectId'
      fullPath: '/portfolio/transfer/$projectId'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutPortfolioTransferProjectIdRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/portfolio/retire/$projectId': {
      id: '/_authenticated/_dashboard-layout/portfolio/retire/$projectId'
      path: '/portfolio/retire/$projectId'
      fullPath: '/portfolio/retire/$projectId'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutPortfolioRetireProjectIdRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/portfolio/project/$holdingId': {
      id: '/_authenticated/_dashboard-layout/portfolio/project/$holdingId'
      path: '/portfolio/project/$holdingId'
      fullPath: '/portfolio/project/$holdingId'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/portfolio/list/$projectId': {
      id: '/_authenticated/_dashboard-layout/portfolio/list/$projectId'
      path: '/portfolio/list/$projectId'
      fullPath: '/portfolio/list/$projectId'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutPortfolioListProjectIdRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard-layout/$source/listing/$listingId_': {
      id: '/_authenticated/_dashboard-layout/$source/listing/$listingId_'
      path: '/$source/listing/$listingId'
      fullPath: '/$source/listing/$listingId'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutSourceListingListingIdRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
  }
}

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardLayoutExploreRoute: typeof AuthenticatedDashboardLayoutExploreRoute
  AuthenticatedDashboardLayoutHistoryRoute: typeof AuthenticatedDashboardLayoutHistoryRoute
  AuthenticatedDashboardLayoutListingsRoute: typeof AuthenticatedDashboardLayoutListingsRoute
  AuthenticatedDashboardLayoutSettingsRoute: typeof AuthenticatedDashboardLayoutSettingsRoute
  AuthenticatedDashboardLayoutPortfolioTransactionsRoute: typeof AuthenticatedDashboardLayoutPortfolioTransactionsRoute
  AuthenticatedDashboardLayoutPortfolioIndexRoute: typeof AuthenticatedDashboardLayoutPortfolioIndexRoute
  AuthenticatedDashboardLayoutSourceListingListingIdRoute: typeof AuthenticatedDashboardLayoutSourceListingListingIdRoute
  AuthenticatedDashboardLayoutPortfolioListProjectIdRoute: typeof AuthenticatedDashboardLayoutPortfolioListProjectIdRoute
  AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRoute: typeof AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRoute
  AuthenticatedDashboardLayoutPortfolioRetireProjectIdRoute: typeof AuthenticatedDashboardLayoutPortfolioRetireProjectIdRoute
  AuthenticatedDashboardLayoutPortfolioTransferProjectIdRoute: typeof AuthenticatedDashboardLayoutPortfolioTransferProjectIdRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardLayoutExploreRoute:
      AuthenticatedDashboardLayoutExploreRoute,
    AuthenticatedDashboardLayoutHistoryRoute:
      AuthenticatedDashboardLayoutHistoryRoute,
    AuthenticatedDashboardLayoutListingsRoute:
      AuthenticatedDashboardLayoutListingsRoute,
    AuthenticatedDashboardLayoutSettingsRoute:
      AuthenticatedDashboardLayoutSettingsRoute,
    AuthenticatedDashboardLayoutPortfolioTransactionsRoute:
      AuthenticatedDashboardLayoutPortfolioTransactionsRoute,
    AuthenticatedDashboardLayoutPortfolioIndexRoute:
      AuthenticatedDashboardLayoutPortfolioIndexRoute,
    AuthenticatedDashboardLayoutSourceListingListingIdRoute:
      AuthenticatedDashboardLayoutSourceListingListingIdRoute,
    AuthenticatedDashboardLayoutPortfolioListProjectIdRoute:
      AuthenticatedDashboardLayoutPortfolioListProjectIdRoute,
    AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRoute:
      AuthenticatedDashboardLayoutPortfolioProjectHoldingIdRoute,
    AuthenticatedDashboardLayoutPortfolioRetireProjectIdRoute:
      AuthenticatedDashboardLayoutPortfolioRetireProjectIdRoute,
    AuthenticatedDashboardLayoutPortfolioTransferProjectIdRoute:
      AuthenticatedDashboardLayoutPortfolioTransferProjectIdRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPurchaseSuccessRoute: typeof AuthenticatedPurchaseSuccessRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardLayoutRoute:
    AuthenticatedDashboardLayoutRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPurchaseSuccessRoute: AuthenticatedPurchaseSuccessRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
